## provide the name of the namespace
namespace:
  name: prod

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: ifNotPresent
## set the number of replicas for an application 
replicaCount: 2

##set the resurces configs
resources:
  requests:
    cpu: 70m
    memory: 256Mi

##set de service configs
service:
  type: ClusterIP
  port: 80

##set the configmap configs
configmap:
  data: "version: 1.17.0"
