## provide the name of the namespace
namespace:
  name: staging

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: ifNotPresent
## set the number of replicas for an application 
replicaCount: 1

##set the resurces configs
resources:
  requests:
    cpu: 50m
    memory: 128Mi

##set de service configs
service:
  type: ClusterIP
  port: 8111

##set the configmap configs
configmap:
  data: "version: 1.18.0"
