## provide the name of the namespace
namespace:
  name: demo

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: alpine
  pullPolicy: ifNotPresent
## set the number of replicas for an application 
replicaCount: 3

##set the resurces configs
resources:
  requests:
    cpu: 50m
    memory: 256Mi

##set de service configs
service:
  type: ClusterIP
  port: 8111

##set the configmap configs
configmap:
  data: "version: alpine"
