apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-helloworld
    tag: latest
  name: python-helloworld
  namespace: test
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: python-helloworld
    tag: latest
  type: ClusterIP
